apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
      - name: http
        port: 80
        protocol: HTTP
        allowedRoutes:
            namespaces:
              from: All

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uni-ride-http-route
  namespace: uni-ride
spec:
  parentRefs:
    - kind: Gateway
      name: nginx-gateway
      namespace: nginx-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /iam-service
      backendRefs:
        - group: ""
          kind: Service
          name: iam-service
          port: 9300
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
    - matches:
        - path:
            type: PathPrefix
            value: /profile-service
      backendRefs:
        - group: ""
          kind: Service
          name: profile-service
          port: 9200
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /