apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gke-lb
spec:
  controllerName: networking.gke.io/gateway

---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: uniride-gateway
  namespace: uni-ride
spec:
  gatewayClassName: gke-lb
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
  addresses:
    - type: IPAddress
      value: "34.98.122.144"

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uniride-route
  namespace: uni-ride
spec:
  parentRefs:
    - name: uniride-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: iam-service
          port: 9300
#    - matches:
#        - path:
#            type: PathPrefix
#            value: /carpools
#      backendRefs:
#        - name: matching-routing-service
#          port: 9200
#    - matches:
#        - path:
#            type: PathPrefix
#            value: /profiles
#      backendRefs:
#        - name: profile-service
#          port: 9100