apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-service
  namespace: uni-ride
  labels:
    app: iam-service
spec:
  selector:
    matchLabels:
      app: iam-service
  template:
    metadata:
      labels:
        app: iam-service
    spec:
      containers:
        - name: iam-service
          image: jhosepmyr/iam-service:1.0.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 9300
          env:
            - name: DB_HOST
              value: iam-database
            - name: DB_PORT
              value: "3325"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: iam-database-secrets
                  key: mysql_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: iam-database-secrets
                  key: mysql_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: iam-database-secrets
                  key: mysql_password
            - name: EMAIL_USER
              value: "erich56000@gmail.com"
            - name: EMAIL_PASS
              value: "bgwq uznp pxgy scaw"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9300
            initialDelaySeconds: 10
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: iam-service
  namespace: uni-ride
  labels:
    app: iam-service
spec:
    selector:
      app: iam-service
    ports:
      - protocol: TCP
        port: 9300
        targetPort: 9300