apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-service
  namespace: uni-ride
  labels:
      app: naming-service
spec:
  selector:
      matchLabels:
        app: naming-service
  template:
      metadata:
        labels:
            app: naming-service
      spec:
        containers:
            - name: naming-service
              image: jhosepmyr/naming-service:1.0.0
              imagePullPolicy: Always
              resources:
                  requests:
                    memory: "512Mi"
                    cpu: "200m"
                  limits:
                    memory: "1Gi"
                    cpu: "500m"
              ports:
                  - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: naming-service
  namespace: uni-ride
  labels:
      app: naming-service
spec:
    selector:
        app: naming-service
    ports:
        - protocol: TCP
          port: 8761
          targetPort: 8761