apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: analytics-database
  namespace: uni-ride
spec:
  selector:
    matchLabels:
      app: analytics-database
  serviceName: analytics-database
  replicas: 1
  updateStrategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: analytics-database
    spec:
      containers:
        - name: mysql
          image: mysql:9.2.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "1Gi"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: analytics-database-secrets
                  key: mysql_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-database-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-database-secrets
                  key: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-database-secrets
                  key: mysql_root_password
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: analytics-init-db
            - mountPath: /var/lib/mysql
              name: analytics-database-data
              subPath: analytics_management
      volumes:
        - name: analytics-init-db
          configMap:
            name: analytics-init-db-configmap
        - name: analytics-database-data
          persistentVolumeClaim:
            claimName: analytics-database-pvc

---

apiVersion: v1
kind: Secret
metadata:
  name: analytics-database-secrets
  namespace: uni-ride
data:
  mysql_db: c3RhZmZfbWFuYWdlbWVudA==
  mysql_password: cGFzc3dvcmQxMjM=
  mysql_root_password: cGFzc3dvcmQxMjM0NQ==
  mysql_user: amhvc2VwbXly

---

apiVersion: v1
kind: Service
metadata:
  name: analytics-database
  namespace: uni-ride
  labels:
    app: analytics-database
spec:
    ports:
      - name: analytics-database
        port: 3306
        protocol: TCP
        targetPort: 3306
    selector:
        app: analytics-database
    type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-database-pvc
  namespace: uni-ride
  labels:
    app: analytics-database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-init-db-configmap
  namespace: uni-ride
  labels:
    app: analytics-init-db
