apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: routing-matching-database
  namespace: uni-ride
spec:
  selector:
    matchLabels:
      app: routing-matching-database
  serviceName: routing-matching-database
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: routing-matching-database
    spec:
      containers:
        - name: mysql
          image: mysql:9.2.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "1Gi"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: routing-matching-database-secrets
                  key: mysql_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: routing-matching-database-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: routing-matching-database-secrets
                  key: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: routing-matching-database-secrets
                  key: mysql_root_password
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: routing-matching-init-db
            - mountPath: /var/lib/mysql
              name: routing-matching-database-data
              subPath: routing-matching_management
      volumes:
        - name: routing-matching-init-db
          configMap:
            name: routing-matching-database-config
        - name: routing-matching-database-data
          persistentVolumeClaim:
            claimName: routing-matching-database-volume-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: routing-matching-database-secrets
  namespace: uni-ride
data:
  mysql_db: c3RhZmZfbWFuYWdlbWVudA==
  mysql_password: cGFzc3dvcmQxMjM=
  mysql_root_password: cGFzc3dvcmQxMjM0NQ==
  mysql_user: amhvc2VwbXly

---

apiVersion: v1
kind: Service
metadata:
  name: routing-matching-database
  namespace: uni-ride
  labels:
    app: routing-matching-database
spec:
  ports:
    - name: routing-matching-database
      port: 3325
      protocol: TCP
      targetPort: 3306
  selector:
    app: routing-matching-database
  type: ClusterIP

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: routing-matching-database-volume-claim
  namespace: uni-ride
  labels:
    app: routing-matching-database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: routing-matching-database-config
  namespace: uni-ride
  labels:
    app: routing-matching-database